### ISSUE TITLE
data.py

### ISSUE THREAD

**Issue by PGeogre** [Logan-Lin/UniTE#1]

**Comment by Logan-Lin** [comment]
Hello there! The 'path_conf.json' just needs to provide two key-value pairs: "meta_path" and "dataset_path", depending on where you want to cache the meta data and where your raw dataset files are stored, respectively.

Sorry that currently there are many rough edges in this repository, including the one you mentioned. I am recently reformatting the codes and hopefully will publish a more polished version soon.
