### ISSUE TITLE
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by Favourte** [Logan-Lin/UniTE#2]
当我在`terminal`中输入`python main.py` 报错：
`ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

**Comment by Logan-Lin** [comment]
Hi, I recently add a "Hands-on" section in the readme, including a guide on how to prepare the runtime environment. Hope this can help you fix the problem you encountered. If not, feel free to open a new issue or contact me directly.
